/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationLayer;

import dataLayer.Link;
import dataLayer.Stack;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Trevi
 */
public class MainFrame extends javax.swing.JFrame {
    Random rn = new Random();
    public Stack numStack = new Stack();
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        taLinks.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldInteger = new javax.swing.JTextField();
        buttonAddLink = new javax.swing.JButton();
        buttonDeleteLink = new javax.swing.JButton();
        buttonAbout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLinks = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Structures Project #1");
        setBackground(new java.awt.Color(240, 240, 234));
        setPreferredSize(new java.awt.Dimension(400, 320));

        textFieldInteger.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        buttonAddLink.setText("Add Link");
        buttonAddLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddLinkActionPerformed(evt);
            }
        });

        buttonDeleteLink.setText("Delete Link");
        buttonDeleteLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteLinkActionPerformed(evt);
            }
        });

        buttonAbout.setText("About");
        buttonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAboutActionPerformed(evt);
            }
        });

        taLinks.setColumns(20);
        taLinks.setRows(5);
        jScrollPane2.setViewportView(taLinks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAddLink, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldInteger, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteLink, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldInteger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDeleteLink, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(buttonAddLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddLinkActionPerformed

        try
        {
            numStack.addLink(parseInt(textFieldInteger.getText()));
            update(numStack.getHead());
            
//            if(taLinks.getText().equals(""))
//            {
//                
//                taLinks.setText(Integer.toString(numStack.getHead().getValue()));
//            }
//            else
//            {
//                taLinks.setText("");
//                
//                update(numStack.getHead());
////                taLinks.append(Integer.toString(numStack.getTopOfStack().getValue()));
//            }            
            
        }
        catch(IllegalArgumentException iex)
        {
            JOptionPane.showMessageDialog(null, "Please enter a 10 digit whole "
                + "number before adding a Link", "Error", JOptionPane.ERROR_MESSAGE);
            textFieldInteger.requestFocusInWindow();
            textFieldInteger.setText("");
        }
        
    }//GEN-LAST:event_buttonAddLinkActionPerformed

    private void buttonDeleteLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteLinkActionPerformed

 
        try{
            numStack.removeLink();
            update(numStack.getHead());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "There are no more links."
                , "Error", JOptionPane.ERROR_MESSAGE);
            textFieldInteger.requestFocusInWindow();
            textFieldInteger.setText("");        
        }



    }//GEN-LAST:event_buttonDeleteLinkActionPerformed

    private void buttonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAboutActionPerformed
                JOptionPane.showMessageDialog(null, 
                  "Assigment:      Data Structures Project #3 \n"
                + "Author:              Johnny Trevino\n"
                + "Project Due:    Sept. 11 2017 NLT 11:59 pm CST\n\n"        
                + "Description: \nThis program implements a queue using a linked list. "
                          + "\nIt allows the user to queue integers on the queue, "
                          + "or de-queue integers off the queue. \nProgram does not crash "
                          + "if the user de-queues an empty queue. \n"
                          + "Note: Program does not use Java’s built in stack or linked list.", 
                "About", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonAboutActionPerformed
    
//    private void populateList(int count){
//        if (count!=0) {
//            numStack.addLink(rn.nextInt(9999 - 1 + 1) + 1);
//            update(numStack.getHead());
//            count--;
//            populateList(count);
//        }
//        
//    }
    
    private void update(Link next)
    {
        

        
        if (numStack.getHead()==null && numStack.getHead()==null) {
            numStack = new Stack();
            taLinks.setText("");
        }
        else{
            taLinks.setText("");
            numStack.resetValueString();
            taLinks.setText(numStack.buildValueString(next));            
        }
        
        textFieldInteger.requestFocusInWindow();
        textFieldInteger.setText("");

    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonAddLink;
    private javax.swing.JButton buttonDeleteLink;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taLinks;
    private javax.swing.JTextField textFieldInteger;
    // End of variables declaration//GEN-END:variables

}
